language: go

os:
  - linux

go:
  - 1.4
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip

  exclude:
    - os: osx
      go: 1.4
    - os: osx
      go: 1.5.x
    - os: osx
      go: 1.6.x

sudo: required
before_install:
  - if [[ $TRAVIS_GO_VERSION == 1.12* ]]; then go get github.com/axw/gocov/gocov github.com/mattn/goveralls; fi
  - sudo apt-get update -qq
  - sudo apt-get install -y fonts-roboto

script:
  - go test -v -tags ci ./...
  - if [[ $TRAVIS_GO_VERSION == 1.12* ]]; then $GOPATH/bin/goveralls -service=travis-ci; fi

notifications:
  email:
    on_success: change
    on_failure: always
